version: "2.4"


services:

  parlez:
    build:
      context: .
    container_name: parlez-bot
    restart: unless-stopped
    runtime: nvidia
    volumes:
      - results:/results  # `OUTPUT_DIRECTORY` in `config.ini`
      # Override config.ini with dynamic one so that the image doesn't need
      # to be rebuilt.
      - config.ini:/usr/src/app/config.ini
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    devices:
      - /dev/dri:/dev/dri
